In [2]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

1/1 [==============================] - 2s 2s/step
[[7.65825625e-10 1.07217835e-04 1.75011024e-04 9.99717653e-01]]
1/1 [==============================] - 0s 49ms/step
[[2.6839309e-09 2.1087664e-05 3.5507651e-07 9.9997854e-01]]
1/1 [==============================] - 0s 178ms/step
[[4.09514023e-09 1.10572955e-05 1.90185233e-07 9.99988675e-01]]
1/1 [==============================] - 0s 108ms/step
[[2.6176703e-09 9.8029614e-06 3.5769793e-07 9.9998987e-01]]
1/1 [==============================] - 0s 103ms/step
[[4.9391797e-09 9.3411263e-06 7.1834830e-07 9.9998999e-01]]
1/1 [==============================] - 0s 109ms/step
[[3.27887473e-09 6.42941586e-06 1.09282645e-07 9.99993443e-01]]
1/1 [==============================] - 0s 54ms/step
[[4.4949351e-09 8.2539354e-06 1.0665649e-07 9.9999166e-01]]
1/1 [==============================] - 0s 63ms/step
[[4.2093218e-09 1.0694743e-05 1.0671503e-07 9.9998915e-01]]
1/1 [==============================] - 0s 53ms/step
[[2.4541047e-09 7.1967333e-06 1.229225