In [2]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

1/1 [==============================] - 1s 1s/step
[[2.8285133e-11 4.2180393e-09 9.9997330e-01 2.6754711e-05]]
1/1 [==============================] - 0s 48ms/step
[[1.3764832e-10 4.8051415e-06 9.9953735e-01 4.5788017e-04]]
1/1 [==============================] - 0s 102ms/step
[[6.5614905e-09 6.0328195e-05 9.8728764e-01 1.2652023e-02]]
1/1 [==============================] - 0s 41ms/step
[[5.0864928e-13 9.8685177e-07 9.9999309e-01 5.9427944e-06]]
1/1 [==============================] - 0s 45ms/step
[[5.4668364e-11 9.5796358e-06 9.9976546e-01 2.2499678e-04]]
1/1 [==============================] - 0s 51ms/step
[[1.9462054e-09 3.6258727e-05 9.9546331e-01 4.5003863e-03]]
1/1 [==============================] - 0s 44ms/step
[[2.1903947e-08 2.2081767e-04 9.7898895e-01 2.0790156e-02]]
1/1 [==============================] - 0s 42ms/step
[[1.1676669e-10 5.5299799e-05 9.9987674e-01 6.7934016e-05]]
1/1 [==============================] - 0s 51ms/step
[[1.1002812e-09 3.5818008e-05 9.9881697e-01 1.1472601

KeyboardInterrupt: 

: 